In [1]:
import numpy as np

In [2]:
list(range(5))

[0, 1, 2, 3, 4]

In [3]:
list(range(0,10))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [5]:
list(range(0.5,2)) #range function only consider integer value

TypeError: 'float' object cannot be interpreted as an integer

In [6]:
#hence numpy used
np.arange(0.4,10.4)

array([0.4, 1.4, 2.4, 3.4, 4.4, 5.4, 6.4, 7.4, 8.4, 9.4])

In [7]:
list(np.arange(0.4,10.4,0.2))

[0.4,
 0.6000000000000001,
 0.8000000000000002,
 1.0000000000000002,
 1.2000000000000002,
 1.4000000000000004,
 1.6000000000000005,
 1.8000000000000003,
 2.0000000000000004,
 2.2000000000000006,
 2.400000000000001,
 2.6000000000000005,
 2.8000000000000007,
 3.000000000000001,
 3.2000000000000006,
 3.400000000000001,
 3.600000000000001,
 3.800000000000001,
 4.000000000000002,
 4.200000000000001,
 4.400000000000002,
 4.600000000000001,
 4.800000000000002,
 5.000000000000002,
 5.200000000000002,
 5.400000000000002,
 5.600000000000002,
 5.8000000000000025,
 6.000000000000002,
 6.200000000000002,
 6.400000000000002,
 6.600000000000002,
 6.8000000000000025,
 7.000000000000003,
 7.200000000000003,
 7.400000000000003,
 7.600000000000003,
 7.8000000000000025,
 8.000000000000002,
 8.200000000000003,
 8.400000000000004,
 8.600000000000003,
 8.800000000000002,
 9.000000000000004,
 9.200000000000003,
 9.400000000000004,
 9.600000000000003,
 9.800000000000004,
 10.000000000000004,
 10.20000000000000

In [8]:
np.linspace(1,5,20)

array([1.        , 1.21052632, 1.42105263, 1.63157895, 1.84210526,
       2.05263158, 2.26315789, 2.47368421, 2.68421053, 2.89473684,
       3.10526316, 3.31578947, 3.52631579, 3.73684211, 3.94736842,
       4.15789474, 4.36842105, 4.57894737, 4.78947368, 5.        ])

In [9]:
#20 division divided 

In [10]:
np.logspace(1,5  ,10)

array([1.00000000e+01, 2.78255940e+01, 7.74263683e+01, 2.15443469e+02,
       5.99484250e+02, 1.66810054e+03, 4.64158883e+03, 1.29154967e+04,
       3.59381366e+04, 1.00000000e+05])

In [11]:
np.logspace(1,5,10,base=2)

array([ 2.        ,  2.72158   ,  3.70349885,  5.0396842 ,  6.85795186,
        9.33223232, 12.69920842, 17.28095582, 23.51575188, 32.        ])

In [12]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [14]:
np.zeros((3,4))  # 3 rows 4 column

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [15]:
np.zeros((3,4,2))  # 3matrix of 4 rows 2 column

array([[[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]]])

In [17]:
arr=np.ones((3,4))

In [18]:
arr

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [19]:
arr+5

array([[6., 6., 6., 6.],
       [6., 6., 6., 6.],
       [6., 6., 6., 6.]])

In [20]:
arr*4

array([[4., 4., 4., 4.],
       [4., 4., 4., 4.],
       [4., 4., 4., 4.]])

In [21]:
np.empty((3,4))

array([[4., 4., 4., 4.],
       [4., 4., 4., 4.],
       [4., 4., 4., 4.]])

In [22]:
np.eye(5)    #1 in diagonal

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [23]:
arr1=np.eye(5)

In [24]:
#to convert this into dataframe

In [25]:
import pandas as pd

In [26]:
arr

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [27]:
pd.DataFrame(arr1)

0    1    2    3    4
0  1.0  0.0  0.0  0.0  0.0
1  0.0  1.0  0.0  0.0  0.0
2  0.0  0.0  1.0  0.0  0.0
3  0.0  0.0  0.0  1.0  0.0
4  0.0  0.0  0.0  0.0  1.0

In [29]:
np.random.rand(2,3)   #2 row 3 column

array([[0.15884927, 0.12615795, 0.30915351],
       [0.72452978, 0.3490835 , 0.98141749]])

In [30]:
np.random.randn(2,3) 

array([[-0.41478717,  1.3516645 , -0.17001695],
       [-0.84487454, -2.00836489,  2.89590042]])

In [31]:
#here in randn mean=0

In [34]:
arr2=np.random.randint(1,5,(3,4))  #data between 1 to 5 and size 3*4

In [35]:
arr2

array([[3, 4, 4, 1],
       [3, 2, 1, 1],
       [4, 2, 4, 1]])

In [36]:
arr2.size

12

In [37]:
arr2.shape

(3, 4)

In [38]:
#change shape
arr2.reshape()

TypeError: reshape() takes exactly 1 argument (0 given)

In [39]:
arr2.reshape(6,2)

array([[3, 4],
       [4, 1],
       [3, 2],
       [1, 1],
       [4, 2],
       [4, 1]])

In [41]:
arr2.reshape(6,3)  #this need 18 datas

ValueError: cannot reshape array of size 12 into shape (6,3)

In [42]:
arr2.reshape(4,-1)

array([[3, 4, 4],
       [1, 3, 2],
       [1, 1, 4],
       [2, 4, 1]])

In [43]:
arr2.reshape(3,-22367583930)

array([[3, 4, 4, 1],
       [3, 2, 1, 1],
       [4, 2, 4, 1]])

In [45]:
arr2.reshape(2,2,3)     # 2matrix of shape 2 by 3

array([[[3, 4, 4],
        [1, 3, 2]],

       [[1, 1, 4],
        [2, 4, 1]]])

In [46]:
arr3=np.random.randint(1,10,(5,6))

In [47]:
arr3

array([[4, 7, 6, 9, 5, 7],
       [2, 8, 5, 9, 5, 9],
       [8, 5, 9, 6, 3, 2],
       [6, 7, 1, 8, 1, 3],
       [6, 9, 3, 3, 8, 8]])

In [49]:
arr3>8

array([[False, False, False,  True, False, False],
       [False, False, False,  True, False,  True],
       [False, False,  True, False, False, False],
       [False, False, False, False, False, False],
       [False,  True, False, False, False, False]])

In [50]:
arr3[arr3>8]

array([9, 9, 9, 9, 9])

In [51]:
arr3

array([[4, 7, 6, 9, 5, 7],
       [2, 8, 5, 9, 5, 9],
       [8, 5, 9, 6, 3, 2],
       [6, 7, 1, 8, 1, 3],
       [6, 9, 3, 3, 8, 8]])

In [52]:
#extract 4 7 i.e row zero column 0,1

In [54]:
arr3[0,[0,1]]

array([4, 7])

In [55]:
arr3[2:4,[2,3]]  #2:4 start from 2 to 4 

array([[9, 6],
       [1, 8]])

In [56]:
arr4=np.random.randint(1,3,(3,3))
arr5=np.random.randint(1,3,(3,3))

In [57]:
arr4

array([[1, 1, 1],
       [1, 1, 1],
       [2, 2, 2]])

In [58]:
arr5

array([[2, 1, 1],
       [2, 2, 2],
       [2, 2, 1]])

In [59]:
arr4+arr5

array([[3, 2, 2],
       [3, 3, 3],
       [4, 4, 3]])

In [61]:
arr4-arr5

array([[-1,  0,  0],
       [-1, -1, -1],
       [ 0,  0,  1]])

In [62]:
arr4*arr5

array([[2, 1, 1],
       [2, 2, 2],
       [4, 4, 2]])

In [63]:
 arr4/arr5

array([[0.5, 1. , 1. ],
       [0.5, 0.5, 0.5],
       [1. , 1. , 2. ]])

In [64]:
arr4/0

C:\Users\rohan\AppData\Local\Temp\ipykernel_22148\1674986024.py:1: RuntimeWarning: divide by zero encountered in divide
  arr4/0


array([[inf, inf, inf],
       [inf, inf, inf],
       [inf, inf, inf]])

In [65]:
# Numpy - Brodcasting
arr6 = np.zeros((3,4))

In [66]:
arr6

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [69]:
arr6+5

array([[5., 5., 5., 5.],
       [5., 5., 5., 5.],
       [5., 5., 5., 5.]])

In [70]:
a=np.array([1,2,3,4])

In [71]:
a

array([1, 2, 3, 4])

In [72]:
arr6+a

array([[1., 2., 3., 4.],
       [1., 2., 3., 4.],
       [1., 2., 3., 4.]])

In [79]:
b=np.array([[3,4,5]])

In [80]:
arr6+b

ValueError: operands could not be broadcast together with shapes (3,4) (1,3) 

In [81]:
#operands could not be broadcast together with shapes (3,4) (3,) 
#use transpose
arr6+b.T

array([[3., 3., 3., 3.],
       [4., 4., 4., 4.],
       [5., 5., 5., 5.]])

In [82]:
b.T

array([[3],
       [4],
       [5]])

In [83]:
arr11=arr6+b.T

In [84]:
arr11

array([[3., 3., 3., 3.],
       [4., 4., 4., 4.],
       [5., 5., 5., 5.]])

In [85]:
np.sqrt(arr1)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [86]:
np.log10(arr11)

array([[0.47712125, 0.47712125, 0.47712125, 0.47712125],
       [0.60205999, 0.60205999, 0.60205999, 0.60205999],
       [0.69897   , 0.69897   , 0.69897   , 0.69897   ]])

In [87]:
np.exp(arr1)

array([[2.71828183, 1.        , 1.        , 1.        , 1.        ],
       [1.        , 2.71828183, 1.        , 1.        , 1.        ],
       [1.        , 1.        , 2.71828183, 1.        , 1.        ],
       [1.        , 1.        , 1.        , 2.71828183, 1.        ],
       [1.        , 1.        , 1.        , 1.        , 2.71828183]])

In [88]:
arr11

array([[3., 3., 3., 3.],
       [4., 4., 4., 4.],
       [5., 5., 5., 5.]])

In [89]:
np.min(arr11)

3.0

In [90]:
np.max(arr11)

5.0

In [91]:
np.mean(arr11)

4.0