In [1]:
import numpy as np

In [2]:
#for array and matrix manimullation
#list to array

In [3]:
l=[1,2,3,4,5,6,7]

In [4]:
arr=np.array(l)

In [5]:
arr

array([1, 2, 3, 4, 5, 6, 7])

In [6]:
type(arr)

numpy.ndarray

In [8]:
np.asarray(l)

array([1, 2, 3, 4, 5, 6, 7])

In [10]:
arr1 = np.array([[1,2,3] , [2,3,4]])  #2D array
arr1

array([[1, 2, 3],
       [2, 3, 4]])

In [13]:
arr1.ndim #check  dimentions

2

In [14]:
#now plot this aaray


In [15]:
#numpy matrixes
np.matrix(l)

matrix([[1, 2, 3, 4, 5, 6, 7]])

In [16]:
mat = np.matrix(l)

In [17]:
mat

matrix([[1, 2, 3, 4, 5, 6, 7]])

In [18]:
np.asanyarray(l)


array([1, 2, 3, 4, 5, 6, 7])

In [19]:
np.asanyarray(mat)

matrix([[1, 2, 3, 4, 5, 6, 7]])

In [20]:
arr

array([1, 2, 3, 4, 5, 6, 7])

In [21]:
arr[0]=100

In [22]:
arr

array([100,   2,   3,   4,   5,   6,   7])

In [23]:
b=np.copy(arr)

In [24]:
b

array([100,   2,   3,   4,   5,   6,   7])

In [25]:
b[0]=234

In [26]:
b

array([234,   2,   3,   4,   5,   6,   7])

In [27]:
arr

array([100,   2,   3,   4,   5,   6,   7])

In [28]:
#b changed but not arr

In [29]:
arr[1]=34

In [30]:
b

array([234,   2,   3,   4,   5,   6,   7])

In [31]:
a=arr

In [32]:
a[2]=23

In [33]:
a

array([100,  34,  23,   4,   5,   6,   7])

In [34]:
arr

array([100,  34,  23,   4,   5,   6,   7])

In [35]:
#functions in mumpy 

In [36]:
np.fromfunction(lambda i,j :i==j,(3,3))

array([[ True, False, False],
       [False,  True, False],
       [False, False,  True]])

In [37]:
np.fromfunction(lambda i,j :i*j,(3,3))

array([[0., 0., 0.],
       [0., 1., 2.],
       [0., 2., 4.]])

In [38]:
list(i*i for i in range(5))

[0, 1, 4, 9, 16]

In [41]:
iterable=(i*i for i in range(5))

In [42]:
np.fromiter(iterable,float)

array([ 0.,  1.,  4.,  9., 16.])

In [44]:
np.fromstring('23 24 56',sep= ' ')

array([23., 24., 56.])

In [45]:
arr

array([100,  34,  23,   4,   5,   6,   7])

In [46]:
arr.ndim

1

In [47]:
arr1.ndim

2

In [48]:
arr.size #total number of elements

7

In [49]:
arr1.size

6

In [50]:
arr.shape

(7,)

In [51]:
arr1.shape

(2, 3)

In [52]:
arr1.dtype

dtype('int32')