In [1]:
'''
Consider the below code to answer further questions:
import numpy as np
list_ = [ ‘1’ , ’2’ , ‘3’ , ‘4’ , ‘5’ ]
array_list = np.array(object = list_)
'''

'\nConsider the below code to answer further questions:\nimport numpy as np\nlist_ = [ ‘1’ , ’2’ , ‘3’ , ‘4’ , ‘5’ ]\narray_list = np.array(object = list_)\n'

In [3]:
import numpy as np
list_ = [ '1','2','3','4','5']
array_list = np.array(object = list_)

In [4]:
print("Data type of list_:", type(list_))
print("Data type of array_list:", type(array_list))

Data type of list_: <class 'list'>
Data type of array_list: <class 'numpy.ndarray'>


In [5]:
print("Data types of elements in list_:")
for element in list_:
    print(type(element))

# Print data types of each element in array_list
print("Data types of elements in array_list:")
for element in array_list:
    print(type(element))

Data types of elements in list_:
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
Data types of elements in array_list:
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>


In [6]:
#q3

In [7]:
array_list = np.array(object=list_, dtype=int)

# Print data types of each element in list_
print("Data types of elements in list_:")
for element in list_:
    print(type(element))

# Print data types of each element in array_list
print("Data types of elements in array_list:")
for element in array_list:
    print(type(element))

Data types of elements in list_:
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
Data types of elements in array_list:
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>


In [8]:
array_list

array([1, 2, 3, 4, 5])

In [9]:
np.shape(array_list) #Q.4

(5,)

In [10]:
np.size(array_list) #Q.4

5

In [11]:
# Q5: Create a 3x3 matrix containing only zeros
zero_matrix = np.zeros((3, 3))
print("Q5: 3x3 Matrix of Zeros:")
print(zero_matrix)

# Q6: Create a 5x5 identity matrix
identity_matrix = np.eye(5)
print("\nQ6: 5x5 Identity Matrix:")
print(identity_matrix)

Q5: 3x3 Matrix of Zeros:
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]

Q6: 5x5 Identity Matrix:
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
