In [1]:
import numpy as np

In [2]:
#Numpy - Array Manipulation

In [3]:
arr=np.random.randint(1,10,(4,4))

In [4]:
arr

array([[3, 5, 3, 1],
       [3, 6, 6, 7],
       [3, 1, 6, 9],
       [4, 3, 3, 5]])

In [5]:
#reshape 
arr.reshape(8,2)

array([[3, 5],
       [3, 1],
       [3, 6],
       [6, 7],
       [3, 1],
       [6, 9],
       [4, 3],
       [3, 5]])

In [6]:
arr.T #transpose (rotate)

array([[3, 3, 3, 4],
       [5, 6, 1, 3],
       [3, 6, 6, 3],
       [1, 7, 9, 5]])

In [7]:
arr.flatten()  # all data in 1 dimention

array([3, 5, 3, 1, 3, 6, 6, 7, 3, 1, 6, 9, 4, 3, 3, 5])

In [8]:
arr

array([[3, 5, 3, 1],
       [3, 6, 6, 7],
       [3, 1, 6, 9],
       [4, 3, 3, 5]])

In [9]:
np.expand_dims(arr)   #expand dimentions 

TypeError: expand_dims() missing 1 required positional argument: 'axis'

In [10]:
np.expand_dims(arr,axis=1)  

array([[[3, 5, 3, 1]],

       [[3, 6, 6, 7]],

       [[3, 1, 6, 9]],

       [[4, 3, 3, 5]]])

In [11]:
np.expand_dims(arr,axis=0)

array([[[3, 5, 3, 1],
        [3, 6, 6, 7],
        [3, 1, 6, 9],
        [4, 3, 3, 5]]])

In [12]:
data=np.array([[1],[2],[3]])

In [13]:
np.squeeze(data)

array([1, 2, 3])

In [14]:
np.repeat(data,2)

array([1, 1, 2, 2, 3, 3])

In [15]:
np.repeat(data,4)

array([1, 1, 1, 1, 2, 2, 2, 2, 3, 3, 3, 3])

In [16]:
np.roll(data,3)     #roll across given axis 

array([[1],
       [2],
       [3]])

In [17]:
np.roll(data,2) 

array([[2],
       [3],
       [1]])

In [18]:
np.roll(data,6) 

array([[1],
       [2],
       [3]])

In [20]:
np.roll(data,4)

array([[3],
       [1],
       [2]])

In [21]:
np.diag(np.array([1,2,3,4]))

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]])

# Numpy - Binary Operators

In [22]:
arr1=np.random.randint(1,10,(3,4))
arr2=np.random.randint(1,10,(3,4))

In [23]:
arr1

array([[9, 9, 9, 4],
       [6, 8, 3, 8],
       [9, 9, 2, 8]])

In [24]:
arr2

array([[2, 6, 1, 5],
       [1, 5, 6, 2],
       [7, 5, 5, 6]])

In [25]:
arr1*arr2

array([[18, 54,  9, 20],
       [ 6, 40, 18, 16],
       [63, 45, 10, 48]])

In [26]:
arr1-arr2

array([[ 7,  3,  8, -1],
       [ 5,  3, -3,  6],
       [ 2,  4, -3,  2]])

In [27]:
arr1**arr2

array([[     81,  531441,       9,    1024],
       [      6,   32768,     729,      64],
       [4782969,   59049,      32,  262144]])

In [28]:
arr1>arr2

array([[ True,  True,  True, False],
       [ True,  True, False,  True],
       [ True,  True, False,  True]])

In [29]:
arr1

array([[9, 9, 9, 4],
       [6, 8, 3, 8],
       [9, 9, 2, 8]])

In [30]:
-arr1

array([[-9, -9, -9, -4],
       [-6, -8, -3, -8],
       [-9, -9, -2, -8]])

# Numpy- String Function

In [31]:
arr=np.array(['rohan','kaitake'])

In [32]:
arr

array(['rohan', 'kaitake'], dtype='<U7')

In [33]:
np.char.upper(arr)

array(['ROHAN', 'KAITAKE'], dtype='<U7')

In [34]:
np.char.capitalize(arr)  #1st latter upper case

array(['Rohan', 'Kaitake'], dtype='<U7')

In [36]:
np.char.title(arr)

array(['Rohan', 'Kaitake'], dtype='<U7')

# Numpy - Mathematical Function

In [37]:
arr1

array([[9, 9, 9, 4],
       [6, 8, 3, 8],
       [9, 9, 2, 8]])

In [38]:
np.sin(arr1)

array([[ 0.41211849,  0.41211849,  0.41211849, -0.7568025 ],
       [-0.2794155 ,  0.98935825,  0.14112001,  0.98935825],
       [ 0.41211849,  0.41211849,  0.90929743,  0.98935825]])

In [39]:
np.cos(arr1)

array([[-0.91113026, -0.91113026, -0.91113026, -0.65364362],
       [ 0.96017029, -0.14550003, -0.9899925 , -0.14550003],
       [-0.91113026, -0.91113026, -0.41614684, -0.14550003]])

In [40]:
np.cos(0)

1.0

In [41]:
np.tan(arr1)

array([[-0.45231566, -0.45231566, -0.45231566,  1.15782128],
       [-0.29100619, -6.79971146, -0.14254654, -6.79971146],
       [-0.45231566, -0.45231566, -2.18503986, -6.79971146]])

In [42]:
np.log10(arr1)

array([[0.95424251, 0.95424251, 0.95424251, 0.60205999],
       [0.77815125, 0.90308999, 0.47712125, 0.90308999],
       [0.95424251, 0.95424251, 0.30103   , 0.90308999]])

In [43]:
np.exp(arr1)

array([[8.10308393e+03, 8.10308393e+03, 8.10308393e+03, 5.45981500e+01],
       [4.03428793e+02, 2.98095799e+03, 2.00855369e+01, 2.98095799e+03],
       [8.10308393e+03, 8.10308393e+03, 7.38905610e+00, 2.98095799e+03]])

In [44]:
np.power(arr1,2)

array([[81, 81, 81, 16],
       [36, 64,  9, 64],
       [81, 81,  4, 64]], dtype=int32)

In [45]:
np.mean(arr1)

7.0

In [46]:
np.median(arr1)

8.0

In [47]:
np.mode(arr1)

AttributeError: module 'numpy' has no attribute 'mode'

In [48]:
pip install scipy


Defaulting to user installation because normal site-packages is not writeable
Note: you may need to restart the kernel to use updated packages.


DEPRECATION: Loading egg at c:\programdata\anaconda3\lib\site-packages\vboxapi-1.0-py3.11.egg is deprecated. pip 23.3 will enforce this behaviour change. A possible replacement is to use pip for package installation..


In [49]:
from scipy.stats import mode

In [50]:
mode(arr1)

C:\Users\rohan\AppData\Local\Temp\ipykernel_4368\1989301069.py:1: FutureWarning: Unlike other reduction functions (e.g. `skew`, `kurtosis`), the default behavior of `mode` typically preserves the axis it acts along. In SciPy 1.11.0, this behavior will change: the default value of `keepdims` will become False, the `axis` over which the statistic is taken will be eliminated, and the value None will no longer be accepted. Set `keepdims` to True or False to avoid this warning.
  mode(arr1)


ModeResult(mode=array([[9, 9, 2, 8]]), count=array([[2, 2, 1, 2]]))

In [66]:
np.std(arr1)  #standard deviation --> dispersion from mean

2.48327740429189

In [67]:
np.var(arr1)

6.166666666666667

In [68]:
np.max(arr1)

9

In [69]:
np.min(arr1)

2

# Numpy - Arithematic Operations

In [70]:
arr1

array([[9, 9, 9, 4],
       [6, 8, 3, 8],
       [9, 9, 2, 8]])

In [71]:
arr2

array([[2, 6, 1, 5],
       [1, 5, 6, 2],
       [7, 5, 5, 6]])

In [72]:
arr1-arr2

array([[ 7,  3,  8, -1],
       [ 5,  3, -3,  6],
       [ 2,  4, -3,  2]])

In [73]:
np.subtract(arr1,arr2)

array([[ 7,  3,  8, -1],
       [ 5,  3, -3,  6],
       [ 2,  4, -3,  2]])

In [74]:
np.multiply(arr1,arr2)

array([[18, 54,  9, 20],
       [ 6, 40, 18, 16],
       [63, 45, 10, 48]])

In [75]:
np.mod(arr1,arr2)

array([[1, 3, 0, 4],
       [0, 3, 3, 0],
       [2, 4, 2, 2]])

In [76]:
np.power(arr1,arr2)

array([[     81,  531441,       9,    1024],
       [      6,   32768,     729,      64],
       [4782969,   59049,      32,  262144]])

In [77]:
arr1**arr2

array([[     81,  531441,       9,    1024],
       [      6,   32768,     729,      64],
       [4782969,   59049,      32,  262144]])

In [78]:
np.sqrt(arr1)

array([[3.        , 3.        , 3.        , 2.        ],
       [2.44948974, 2.82842712, 1.73205081, 2.82842712],
       [3.        , 3.        , 1.41421356, 2.82842712]])