In [1]:
import numpy as np

# Sort ,search and counting functions

In [10]:
arr=np.array([4,2,6,7,1,8,9,5])

In [11]:
arr

array([4, 2, 6, 7, 1, 8, 9, 5])

In [12]:
np.sort(arr)

array([1, 2, 4, 5, 6, 7, 8, 9])

In [13]:
np.searchsorted(arr,6) 

5

In [14]:
#6 is at 5th index

In [16]:
arr1=np.array([0,323,654,244,6,7,9,0,0,0,6,6,6,232])

In [18]:
np.count_nonzero(arr1)

10

In [19]:
np.where(arr1>0)

(array([ 1,  2,  3,  4,  5,  6, 10, 11, 12, 13], dtype=int64),)

In [20]:
np.extract(arr1>2,arr1)

array([323, 654, 244,   6,   7,   9,   6,   6,   6, 232])

# Numpy -Byte Swapping 

In [21]:
#not much necessary 

In [22]:
#for every ddata gives byte

In [23]:
arr1


array([  0, 323, 654, 244,   6,   7,   9,   0,   0,   0,   6,   6,   6,
       232])

In [26]:
arr1.byteswap()

array([          0,  1124139008, -1912471552,  -201326592,   100663296,
         117440512,   150994944,           0,           0,           0,
         100663296,   100663296,   100663296,  -402653184])

# copies & Views

In [27]:
arr1

array([  0, 323, 654, 244,   6,   7,   9,   0,   0,   0,   6,   6,   6,
       232])

In [28]:
a=np.copy(arr1)

In [29]:
a

array([  0, 323, 654, 244,   6,   7,   9,   0,   0,   0,   6,   6,   6,
       232])

In [30]:
b=np.view()

AttributeError: module 'numpy' has no attribute 'view'

In [31]:
b=arr1.view()

In [32]:
b

array([  0, 323, 654, 244,   6,   7,   9,   0,   0,   0,   6,   6,   6,
       232])

In [34]:
#view is swallow copy 

In [35]:
b[0]

0

In [36]:
b[0]=23

In [37]:
arr1

array([ 23, 323, 654, 244,   6,   7,   9,   0,   0,   0,   6,   6,   6,
       232])

# numpy Matrix Library 

In [38]:
import numpy.matlib as nm

In [39]:
nm.zeros(5)

matrix([[0., 0., 0., 0., 0.]])

In [40]:
nm.ones(3,4)

TypeError: Cannot interpret '4' as a data type

In [41]:
nm.ones((3,4))

matrix([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [43]:
nm.eye(4)  #one in diagonal 

matrix([[1., 0., 0., 0.],
        [0., 1., 0., 0.],
        [0., 0., 1., 0.],
        [0., 0., 0., 1.]])

# Linear Algebra

In [44]:
arr1

array([ 23, 323, 654, 244,   6,   7,   9,   0,   0,   0,   6,   6,   6,
       232])

In [45]:
arr2=np.random.randint([[2,3],[4,5]])

In [46]:
arr3=np.random.randint([[5,3],[2,5]])

In [47]:
arr2

array([[1, 2],
       [1, 2]])

In [48]:
arr3

array([[0, 1],
       [1, 4]])

In [51]:
np.dot(arr2,arr3) #dot product

array([[2, 9],
       [2, 9]])

In [54]:
arr2@arr3  #dot product

array([[2, 9],
       [2, 9]])